"""
Contains information about an artist that illustrated a magic card.
"""
type Artist {
  """
  Returns an array of cards that the artist has illustrated.
  """
  cards(
    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int
  ): CardConnection

  """
  Returns the name of an artist.
  """
  identifier: String
}

"""
Contains informaiton about a magic set block.
"""
type Block {
  """
  Returns the name of the block. E.g., Zendikar, Mirrodin, etc.
  """
  identifier: String

  """
  Returns a list of sets that are in this block. E.g., If the block is Zendikar,
  the sets Zendikar, Worldwake, and Rise of the Eldrazi will be returned.
  """
  magicSets: [MagicSet]
}

"""
Contains information about a booster pack for a magic set.
"""
type Booster {
  """
  Returns descriptive information about a card slot in the booster pack.
  """
  cardDescription: CardDescription

  """
  Returns the slot a card classification can be found in the booster pack.
  """
  position: Int
}

"""
Contains information about magic cards.
"""
type Card {
  """
  Returns information about the artist who illustrated the card.
  """
  artist: Artist

  """
  Returns the border color of the magic card. This field will return null, black, silver, or white.
  """
  borderColor: String

  """
  Returns the card type as printed on the magic card. The card type includes the
  subtype, supertype, and type of the magic card.
  """
  cardType: String

  """
  Returns a list of color identities for the magic card.
  """
  colorIdentities: [Color]

  """
  Returns a list of color indicators for the magic card.
  """
  colorIndicators: [Color]

  """
  Returns a list of colors for the magic card.
  """
  colors: [Color]

  """
  Returns the converted mana cost of the magic card.
  """
  convertedManaCost: Int

  """
  Returns the name of the duel deck it is released in.
  """
  duelDeck: String

  """
  Returns the face converted mana cost of the card.
  """
  faceConvertedManaCost: Float

  """
  Returns the flavour text printed on the magic card.
  """
  flavorText: String

  """
  Returns the foreign data associated with this magic card.
  """
  foreignData: [ForeignDatum]

  """
  Returns the frame effect of the card.
  """
  frameEffect: String

  """
  Returns the frame version of the card.
  """
  frameVersion: String

  """
  Returns the maximum hand size modifier. This field returns null, except for Vanguard cards.
  """
  hand: Int

  """
  Returns whether the card has a foil version.
  """
  hasFoil: Boolean

  """
  Returns whether the card has a non-foil version.
  """
  hasNonFoil: Boolean

  """
  Returns the id of the magic card. The id is a 40 character alphanumeric string.
  """
  id: String

  """
  Returns whether the card is an alternate version.
  """
  isAlternate: Boolean

  """
  Returns whether the card is only printed in foil.
  """
  isFoilOnly: Boolean

  """
  Returns whether the card is only available online.
  """
  isOnlineOnly: Boolean

  """
  Returns whether the card is oversized.
  """
  isOversized: Boolean

  """
  Returns whether the card is on the reserved list.
  """
  isReserved: Boolean

  """
  Returns whether the card is timeshifted.
  """
  isTimeshifted: Boolean

  """
  Returns the layout of the magic card.
  """
  layout: Int

  """
  Returns the legality of the card in various formats.
  """
  legalities: JSON

  """
  Returns the starting life total modifier. This field returns null, except for Vanguard cards.
  """
  life: Int

  """
  Returns the loyalty value of the magic card.
  """
  loyalty: Int

  """
  Returns information about the magic set this card is included in.
  """
  magicSet: MagicSet

  """
  Returns the mana cost of the magic card.
  """
  manaCost: String

  """
  Returns the multiverse id of the magic card.
  """
  multiverseId: Int

  """
  Returns the name as printed on the magic card.
  """
  name: String

  """
  Returns the names as printed on the magic card.
  """
  names: [String]

  """
  Returns the set number of the magic card.
  """
  number: String

  """
  Returns the original text on the card.
  """
  originalText: String

  """
  Returns the original type on the card.
  """
  originalType: String

  """
  Returns the power of the magic card.
  """
  power: String

  """
  Returns the magic sets in which a version of this card was printed.
  """
  printings: [MagicSet]

  """
  Returns the rarity of the magic card.
  """
  rarity: String

  """
  Returns the rulings associated with this magic card.
  """
  rulings: [Ruling]

  """
  Returns the scryfall id of the card
  """
  scryfallId: String

  """
  If printed in a duel deck, returns the side of the duel deck its printed in.
  """
  side: String

  """
  Returns whether the magic card was released in a core box set.
  """
  starter: Boolean

  """
  Returns a list of subtypes for the magic card.
  """
  subtypes: [Subtype]

  """
  Returns a list of supertypes for the magic card.
  """
  supertypes: [Supertype]

  """
  Returns the tcgplayer product id of the card
  """
  tcgplayerProductId: String

  """
  Returns the text inside of the rules box on the card.
  """
  text: String

  """
  Returns a list of tokens that are referenced by this card.
  """
  tokens: [Token]

  """
  Returns the toughness of the magic card.
  """
  toughness: String

  """
  Returns a list of types for the magic card.
  """
  types: [Type]

  """
  Returns a list of the variations of the magic card.
  """
  variants: [Card]

  """
  Returns the watermark on the magic card. If there is no watermark, this field returns null.
  """
  watermark: String
}

"""
Returns paginated information about magic the gathering cards.
"""
type CardConnection {
  """
  A list of edges.
  """
  edges: [CardEdge]

  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!

  """
  Returns the total number of nodes found by the query.
  """
  totalCount: Int
}

"""
Contains information about card slots in a booster pack.
"""
type CardDescription {
  """
  Returns the rarity or classification of a card slot in a booster pack. E.g. Common, Mythic, etc.
  """
  identifier: String
}

"""
An edge in a connection.
"""
type CardEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!

  """
  The item at the end of the edge.
  """
  node: Card
}

input CardFilter {
  """
  Allows you to chain multiple card filters.
  """
  OR: [CardFilter]

  """
  Allows you to search for a magic card by name.
  """
  name: String

  """
  Allows you to search for a magic card similar to a name.
  """
  nameLike: String

  """
  Allows you to search for a magic card by subtype.
  """
  subtype: String

  """
  Allows you to search for a magic card by supertype.
  """
  supertype: String

  """
  Allows you to search for a magic card by type.
  """
  type: String
}

"""
Returns information about magic card colors.
"""
type Color {
  """
  Returns the full name of magic card colors. This field returns Blue, Black, White, Green, or Red.
  """
  identifier: String
}

"""
Contains information about magic cards in other languages.
"""
type ForeignDatum {
  """
  Returns the type of the magic card.
  """
  cardType: String

  """
  Returns the flavor text of the magic card.
  """
  flavorText: String

  """
  Returns the language of the translation.
  """
  language: String

  """
  Returns the multiverse id of the magic card.
  """
  multiverseId: Int

  """
  Returns the name of the magic card.
  """
  name: String

  """
  Returns the text of the magic card.
  """
  text: String
}

scalar JSON

"""
Contains information about a magic the gathering set.
"""
type MagicSet {
  """
  Returns base set size of the magic set.
  """
  baseSetSize: Int

  """
  Returns information about the block the magic set is a part of.
  """
  block: Block

  """
  Returns the structure of a booster pack in this magic set.
  """
  booster: [Booster]

  """
  Returns paginated information about the cards in the magic set.
  """
  cards(
    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int
  ): CardConnection

  """
  Returns the code of the magic set.
  """
  code: String

  """
  Returns whether the magic set was only released online.
  """
  isFoilOnly: Boolean

  """
  Returns whether the magic set was only released online.
  """
  isOnlineOnly: Boolean

  """
  Returns the meta date property of the magic set.
  """
  metaDate: String

  """
  Returns the meta version property of the magic set.
  """
  metaVersion: String

  """
  Returns the mtgo code of the magic set.
  """
  mtgoCode: String

  """
  Returns the name of the magic set.
  """
  name: String

  """
  Returns the release date of the magic set.
  """
  releaseDate: String

  """
  Returns the type of the magic set. E.g., starter, commander, core, etc.
  """
  setType: String

  """
  Returns the tcgplayer group id of the magic set.
  """
  tcgplayerGroupId: String

  """
  Returns paginated information about the tokens in the magic set.
  """
  tokens(
    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int
  ): TokenConnection

  """
  Returns the total set size of the magic set.
  """
  totalSetSize: String
}

"""
Returns paginated information about magic the gathering sets.
"""
type MagicSetConnection {
  """
  A list of edges.
  """
  edges: [MagicSetEdge]

  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!

  """
  Returns the total number of nodes found by the query.
  """
  totalCount: Int
}

"""
An edge in a connection.
"""
type MagicSetEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!

  """
  The item at the end of the edge.
  """
  node: MagicSet
}

input MagicSetFilter {
  """
  Allows you to chain multiple card filters.
  """
  OR: [MagicSetFilter]

  """
  Allows you to search for a magic set by name.
  """
  name: String
}

"""
Information about pagination in a connection.
"""
type PageInfo {
  """
  When paginating forwards, the cursor to continue.
  """
  endCursor: String

  """
  When paginating forwards, are there more items?
  """
  hasNextPage: Boolean!

  """
  When paginating backwards, are there more items?
  """
  hasPreviousPage: Boolean!

  """
  When paginating backwards, the cursor to continue.
  """
  startCursor: String
}

type Query {
  """
  Returns structured information about magic card types.
  """
  CardTypes: [Type]

  """
  Returns paginated information about magic cards.
  """
  Cards(
    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Returns nodes that satisfy the filter arguments.
    """
    filter: CardFilter

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int

    """
    Returns nodes ordered by the specified field.
    """
    order: [String]
  ): CardConnection

  """
  Returns structured information about magic card colors.
  """
  Colors: [Color]

  """
  Returns paginated information about magic sets.
  """
  MagicSets(
    """
    Returns the elements in the list that come after the specified cursor.
    """
    after: String

    """
    Returns the elements in the list that come before the specified cursor.
    """
    before: String

    """
    Return nodes that satisfy the filter arguments.
    """
    filter: MagicSetFilter

    """
    Returns the first _n_ elements from the list.
    """
    first: Int

    """
    Returns the last _n_ elements from the list.
    """
    last: Int

    """
    Return nodes ordered by the specified field.
    """
    order: [String]
  ): MagicSetConnection

  """
  Returns structured information about magic card subtypes.
  """
  Subtypes: [Subtype]

  """
  Returns structured information about magic card supertypes.
  """
  Supertypes: [Supertype]
}

"""
Contains information about magic card rulings.
"""
type Ruling {
  """
  Returns the date of the ruling.
  """
  date: String

  """
  Returns the explanation of the ruling.
  """
  text: String
}

"""
Contains information about magic card subtypes.
"""
type Subtype {
  """
  Returns the name of the subtype. E.g., Merfolk, Wizard, etc.
  """
  identifier: String
}

"""
Contains information about magic card supertypes.
"""
type Supertype {
  """
  Returns the name of the supertype. E.g., Basic, Legendary, etc.
  """
  identifier: String
}

"""
Contains information about magic token.
"""
type Token {
  """
  Returns information about the artist who illustrated the token.
  """
  artist: Artist

  """
  Returns the border color of the magic token. This field will return null, black, silver, or white.
  """
  borderColor: String

  """
  Returns a list of cards that reference this token.
  """
  cards: [Card]

  """
  Returns a list of color identities for the magic token.
  """
  colorIdentities: [Color]

  """
  Returns a list of color indicators for the magic token.
  """
  colorIndicators: [Color]

  """
  Returns a list of colors for the magic token.
  """
  colors: [Color]

  """
  Returns the id of the magic token. The id is a 40 character alphanumeric string.
  """
  id: String

  """
  Returns whether the token is only available online.
  """
  isOnlineOnly: Boolean

  """
  Returns the loyalty value of the magic token.
  """
  loyalty: Int

  """
  Returns information about the magic set this token is included in.
  """
  magicSet: MagicSet

  """
  Returns the name as printed on the magic token.
  """
  name: String

  """
  Returns the set number of the magic token.
  """
  number: String

  """
  Returns the power of the magic token.
  """
  power: String

  """
  Returns the scryfall id of the token
  """
  scryfallId: String

  """
  If printed in a duel deck, returns the side of the duel deck its printed in.
  """
  side: String

  """
  Returns the text inside of the rules box on the token.
  """
  text: String

  """
  Returns the token type as printed on the magic token. The token type includes
  the subtype, supertype, and type of the magic token.
  """
  tokenType: String

  """
  Returns the toughness of the magic token.
  """
  toughness: String

  """
  Returns the watermark on the magic token. If there is no watermark, this field returns null.
  """
  watermark: String
}

"""
Returns paginated information about magic the gathering tokens.
"""
type TokenConnection {
  """
  A list of edges.
  """
  edges: [TokenEdge]

  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!

  """
  Returns the total number of nodes found by the query.
  """
  totalCount: Int
}

"""
An edge in a connection.
"""
type TokenEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!

  """
  The item at the end of the edge.
  """
  node: Token
}

"""
Contains information about the type of a magic card.
"""
type Type {
  """
  Returns the name of the card type. E.g., Instant, Land, Enchantment etc.
  """
  identifier: String
}