# Alternative name for a magic set.
type AlternativeName {
  # The alternative name
  identifier: String

  # Returns a list of magic sets that the alternative name belongs to.
  magicSet: MagicSet
}

# Artist Information.
type Artist {
  # Returns a list of cards that the artist has illustrated.
  cards(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the last _n_ elements from the list.
    last: Int
  ): CardConnection

  # Artist name
  identifier: String
}

# Block Information.
type Block {
  # The name of the block. E.g., Zendikar, Mirrodin, etc.
  identifier: String

  # Returns a list of sets that are in this block. E.g., If the block is Zendikar,
  # the sets Zendikar, Worldwake, and Rise of the Eldrazi will be returned.
  magicSets: [MagicSet]
}

# Booster Information.
type Booster {
  # Describes the card rarity / classification.
  cardDescription: CardDescription

  # The position the card can be found in the pack.
  position: Int
}

# Card information.
type Card {
  # Artist information.
  artist: Artist

  # The border of the card. Return values are null, black, silver, white
  border: String

  # The full card type as written. Includes subtype, supertype, and type.
  cardType: String

  # Converted mana cost
  cmc: Int

  # Returns a list of the card's color identities.
  colorIdentities: [ColorIdentity]

  # Returns a list of the card's colors.
  colors: [Color]

  # Flavor text for the card.
  flavor: String

  hand: Int

  id: String

  imageName: String

  layout: Int

  life: Int

  loyalty: Int

  # The Magic set this card belongs to.
  magicSet: MagicSet

  manaCost: String

  mciNumber: String

  multiverseid: Int

  # The name of the card.
  name: String

  # The number of the card within a set.
  number: String

  power: String

  rarity: String

  # Doesn't exist for all cards. Use Magic Set release date as a fallback.
  releaseDate: String

  # Returns whether the card is on the reserved list.
  reserved: Boolean

  starter: Boolean

  # Returns a list of the card's subtypes.
  subtypes: [Subtype]

  # Returns a list of the card's supertypes.
  supertypes: [Supertype]

  # Card rules text.
  text: String

  # Returns whether the card is timeshifted.
  timeshifted: Boolean

  toughness: String

  # Returns a list of the card's types.
  types: [Type]

  # Returns a list of card variants.
  variants: [Card]

  watermark: String
}

# Returns paginated card information.
type CardConnection {
  # A list of edges.
  edges: [CardEdge]

  # Information to aid in pagination.
  pageInfo: PageInfo!

  # Total number of nodes in the query.
  totalCount: Int
}

# Card Description Type.
type CardDescription {
  # The rarity / classification of a card. E.g. Common, Mythic, etc.
  identifier: String
}

# An edge in a connection.
type CardEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: Card
}

input CardFilter {
  OR: [CardFilter]
  name: String
  subtype: String
  supertype: String
  type: String
}

# Card color information.
type Color {
  # Name of card colors. E.g., Blue, Black, White, etc.
  identifier: String
}

# Card color identity information.
type ColorIdentity {
  # Name of card color identities. E.g., U, B, etc.
  identifier: String
}

# Magic rarity code information. Only appears in older magic sets.
type MagicRaritiesCode {
  # Magic rarities code.
  identifier: String

  magicSet: MagicSet
}

type MagicSet {
  # Returns a list of alternative names for the magic set.
  alternativeNames: [AlternativeName]

  # A magic set's block information.
  block: Block

  # Booster information.
  boosters: [Booster]

  # Border type of cards in the set. Returns either nil, silver, black, or white.
  border: String

  # Returns paginated card information.
  cards(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the last _n_ elements from the list.
    last: Int
  ): CardConnection

  code: String

  gathererCode: String

  magicCardsInfoCode: String

  # Returns a list of magic rarities codes.
  magicRaritiesCodes: [MagicRaritiesCode]

  mkmName: String

  mkm_id: Int

  name: String

  oldCode: String

  onlineOnly: Boolean

  releaseDate: String

  # Returns the type of the set. E.g., starter, commander, core, etc.
  setType: String

  # Returns a list of translations for the name of a magic set.
  translations: [Translation]
}

# Returns paginated magic set information.
type MagicSetConnection {
  # A list of edges.
  edges: [MagicSetEdge]

  # Information to aid in pagination.
  pageInfo: PageInfo!

  # Total number of nodes in the query.
  totalCount: Int
}

# An edge in a connection.
type MagicSetEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: MagicSet
}

input MagicSetFilter {
  OR: [MagicSetFilter]
  name: String
}

# Information about pagination in a connection.
type PageInfo {
  # When paginating forwards, the cursor to continue.
  endCursor: String

  # When paginating forwards, are there more items?
  hasNextPage: Boolean!

  # When paginating backwards, are there more items?
  hasPreviousPage: Boolean!

  # When paginating backwards, the cursor to continue.
  startCursor: String
}

type Query {
  # Card type information.
  CardTypes: [Type]

  # Paginated card information
  Cards(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the elements that satisfy the filter arguments.
    filter: CardFilter

    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the last _n_ elements from the list.
    last: Int

    # Returns the elements ordered by the specified field.
    order: [String]
  ): CardConnection

  # Color identity information.
  ColorIdentities: [ColorIdentity]

  # Color information.
  Colors: [Color]
  MagicSets(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the elements that satisfy the filter arguments.
    filter: MagicSetFilter

    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the last _n_ elements from the list.
    last: Int

    # Returns the elements ordered by the specified field.
    order: [String]
  ): MagicSetConnection

  # Card subtype information.
  Subtypes: [Subtype]

  # Card supertype information.
  Supertypes: [Supertype]
}

type Subtype {
  # Name of card subtype. E.g., Merfolk, Wizard, etc.
  identifier: String
}

type Supertype {
  # Name of card supertype. E.g., Basic, Legendary, etc.
  identifier: String
}

type Translation {
  code: String

  identifier: String

  magicSet: MagicSet
}

type Type {
  # Name of card type. E.g., Instant, Land, Enchantment etc.
  identifier: String
}