version: 2
jobs:
  build:
    working_directory: ~/mtg-graphql-api
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: mtg-graphql-api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: mv circle.env .env

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: mtg-graphql-api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: sudo apt-get install -y nodejs

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:create db:schema:load

      # run rubocop
      - run: bundle exec rubocop

      # Run the tests
      - run: bundle exec rails t
